apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scale
  template:
    metadata:
      labels:
        app: scale
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: scale-svc
          imagePullPolicy: Always
          image: ghcr.io/unfamousthomas/thesis-example-service:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: scale-deployment-service
spec:
  type: ClusterIP
  selector:
    app: scale
  ports:
    - port: 8080
      targetPort: 8080