apiVersion: network.unfamousthomas.me/v1alpha1
kind: GameType
metadata:
  name: gametype-server-sample
  labels:
    gameserver: minecraft
spec:
  fleetSpec:
    scaling:
      replicas: 3
      prioritizeAllowed: true
      agePriority: oldest_first
    spec:
      timeout: 5m
      allowForceDelete: false
      pod:
        imagePullSecrets:
          - name: ghcr-secret
        containers:
          - name: minestom-container
            imagePullPolicy: Always
            image: ghcr.io/unfamousthomas/thesis-example-server:latest
            env:
              - name: "SERVER_ADDRESS"
                value: "http://scale-deployment-service:8080"
            ports:
              - containerPort: 25565
                protocol: TCP